services:
  postgres:
    environment:
      - SEED_DATA=true
    # Тук могат да се добавят специфични за разработка настройки
    # Например, излагане на допълнителни портове или обемни връзки (volumes)
